name: 👾 Bug Report
description: Report a bug
labels: bug
body:
- type: textarea
  attributes:
    label: Reproduction steps
    description: "Tell us what you have done in order for the bug to appear"
    render: bash
  validations:
    required: true
- type: textarea
  attributes:
    label: What have you tried?
    description: Tell us what you have already tried to avoid the bug
  validations:
    required: true
- type: textarea
  attributes:
    label: Logs
    placeholder: You can find the log file in the Roaming folder of the AppData directory
    description: Insert the content of the log file into this textarea
  validations:
    required: true
- type: dropdown
  attributes:
    label: Exception
    options:
      - Exception
      - ArgumentNullException
      - ArgumentOutOfRangeException
      - DirectoryNotFoundException
      - DriveNotFoundException
      - FileNotFoundException
      - InvalidOperationException
      - NotImplementedException
      - NotSupportedException
      - OutOfMemoryException
      - PlatformNotSupportedException
      - TimeoutException
      - UnauthorizedAccessException
      - WarningException
    default: 0
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Operating System
    description: Select the operating systems you have encountered this bug on
    options:
      - label: ♥️ Windows
- type: dropdown
  attributes:
    label: Phone model
    options:
      - Lumia 930
      - Lumia 929 Icon
      - Lumia 1520
      - Lumia 1520 AT & T
      - Lumia 830 Global
      - Lumia 735 Global
      - Lumia 650
      - Lumia 640 XL LTE Global
      - Lumia 640 XL LTE AT & T
      - Lumia 520
      - Lumia 920
      - Lumia 1020
      - Lumia 1020 AT & T
    default: 6
  validations:
    required: true
