name: 👾 Bug Report
description: Report a bug
labels: bug
body:
- type: textarea
  attributes:
    label: Reproduction steps
    description: "Tell us what you have done in order for the bug to appear"
    render: bash
  validations:
    required: true
- type: dropdown
  attributes:
    label: ExceptionType
    options:
      - Exception
    default: 0
- type: textarea
  attributes
    label: Possible ways to fix
    placeholder: Think about what could have caused the bug
- type: checkboxes
  attributes:
    label: Operating System
    description: Select the operating systems you have encountered this bug on
    options:
      - label: 💩 macOS
      - label: ♥️ Windows
      - label: 🤖 Linux
- type: dropdown
  attributes:
    label: Phone model
    options:
      - Lumia 930
      - Lumia 929 (Icon)
      - Lumia 1520
      - Lumia 1520 AT & T
      - Lumia 830 Global
      - Lumia 735 Global
      - Lumia 650
      - Lumia 640 XL LTE Global
      - Lumia 640 XL LTE AT & T
      - Lumia 520
      - Lumia 920
      - Lumia 1020
      - Lumia 1020 AT & T
    default: 6
  validations:
    required: true
- type: dropdown
  attributes:
    label: Which windowsARM version did you used?
    options:
      - 1.0.15
      - 1.0.14
    default: 0
  validations:
    required: true
