name: 👾 Bug Report
description: Report a bug
labels: bug
body:
- type: markdown
  attributes:
    value: "Thanks for taking the time to report a bug 👻"
- type: textarea
  attributes:
    label: Reproduction steps
    description: "Tell us what you have done in order for the bug to appear"
    render: bash
  validations:
    required: true
- type: dropdown
  attributes:
    label: Phone model
    options:
      - Lumia 930
      - Lumia 929 (Icon)
      - Lumia 1520
      - Lumia 1520 AT & T
      - Lumia 830 Global
      - Lumia 735 Global
      - Lumia 650
      - Lumia 640 XL LTE Global
      - Lumia 640 XL LTE AT & T
      - Lumia 520
      - Lumia 920
      - Lumia 1020
      - Lumia 1020 AT & T
    default: 6
  validations:
    required: true
